version: '3'

services:
  app:
    build:
      context: ./app/
    env_file:
      - .env
    volumes:
      - ./app/:/opt/app/
    ports:
      - 127.0.0.1:8000:8000
    command: sh -c "python /opt/app/src/manage.py runserver 0.0.0.0:8000"
    depends_on:
      - postgres
  postgres:
    image: postgres:16.0
    ports:
      - "5432:5432"
    env_file:
      - .env
    volumes:
      - postgres_data:/var/lib/postgresql/data
volumes:
  postgres_data:
